# Generated by Django 3.2.6 on 2021-09-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('due', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('use', models.CharField(max_length=32)),
            ],
        ),
    ]
