# Generated by Django 3.2.6 on 2021-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_me_api', '0002_remove_user_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='income',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='income',
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
